image: openjdk:9-jdk

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  only:
    - master
  script:
    - ./gradlew fatJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week


stages:
  - build
