image: openjdk:9-jdk

stages:
  - build
  - publish

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  only:
    - master
  script:
    - ./gradlew fatJar
  artifacts:
    name: "burp-plugin"
    paths:
      - build/libs/*.jar
    expire_in: 1 week


publish_files:
    stage: publish
    image: 'google/cloud-sdk:latest'
    before_script:
        - check_not_skipped(){ grep -v 'Skipping'; }
        - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
        - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
        - export PLUGIN_VERSION=$(grep -nr 'EXTENSION_VERSION =' * | cut -f2 -d= | tr -d \" | tr -d \; | tr -d '[:space:]')
    script:
        - ls build.libs
        - gsutil cp -Rn faraday-burp-v$PLUGIN_VERSION.jar gs://faraday-build/burp/faraday-burp-latest.jar 2>&1 | check_not_skipped"

    dependencies:
        - build
